### ISSUE TITLE
Failed deploy with Ghost 0.5.8 on Azure Website

### ISSUE THREAD

**Issue by masonkmeyer** [felixrieseberg/Ghost-Updater-Azure#4]
When I upgraded the site, it failed to start. By looking at the Kudu console, I noticed that npm had failed. My upgraded site was missing its package.json file. I manually uploaded the package.json and ran "npm install" but it failed again with the following error: 

```node "D:\Program Files (x86)\npm\1.4.28\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\home\site\wwwroot\node_modules\testem\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\home\site\wwwroot\node_modules\testem\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\binding.sln]```

I suspect it is a limitation with Azure website. Does the updater need to build the node packages before uploading them?

**Comment by felixrieseberg** [comment]
Thanks for reporting! I haven't seen this error before *and* successfully upgraded a bunch do sites to 0.5.8, so I'm eager to find out what happened here.

Which version did you upgrade from?

**Comment by masonkmeyer** [comment]
I am on an older version (0.4.0). I am not sure what happened. I reverted to the backup (which worked fine). I could never find any detailed logs and I suspect it is because I run on a shared Azure website. 

I noticed a few other oddities (index.js wasn't copied and some of the core files were missing). I will try it again. It seems like a very handy tool. @felixrieseberg any suggestions on finding the correct error log? I think one of the powershell scripts failed.

**Comment by felixrieseberg** [comment]
Hey @masonkmeyer, you can find logs on your website by going to yourwebsite.scm.azurewebsites.net. Click on 'Debug' and then 'Powershell' to get access to all files on your server, including the logs.

I have concluded that updating from a version this old might be too difficult to implement into the updater, but I'm happy to walk you through a manual update. As soon as you're on anything above 5, you will be fine with the upgrader :smile:. Shoot me a mail at feriese@microsoft.com if you want the help!

I'll be closing this in the meantime.
